define("page/page_appoint_temp", function(a, b, c) {
	// js引擎模板
	var tmpHtml = '<script id="tmp_appoint" type="text/html">'
					+'<div id="page_appoint" class="page_appoint{{productInfo._id}}">'
						+'<input type="hidden" value="在线预约" id="wx_title_appoint" />'
						+'<input type="hidden" value="{{storeInfo.logo}}?imageView2/0/w/320" id="wx_imgUrl_appoint" />'
						+'<input type="hidden" value="{{storeInfo.userInfo.nickname}}的微官网" id="wx_desc_appoint" />'
						+'<div id="part1">'
							+'<div class="pTop">'
								+'<a href="#page_fwdetail/{{productInfo._id}}" class="back"></a>'
								+'<a href="#page_detail/" class="backhome"></a>'
								+'<div>服务预约</div>'
							+'</div>'
							+'<input type="hidden" value="预约" id="title_appoint" />'
							+'<div class="main">'
								+'<div class="blank"></div>'
								+'<div class="dabbox ap_storeInfo">'
									+'<div class="storeInfoImg">'
										+'<img src="{{productInfo.images[0]}}?imageView2/1/w/80/h/80" alt="" />'
									+'</div>'
									+'<div class="storeInfoMsg">'
										+'<h2>{{productInfo.title}}</h2>'
										+'<p>价格：<span style="color:#1a1a1a">{{productInfo.price}}</span></p>'
										+'<p>预付定金：<span style="color:#1a1a1a">{{productInfo.price}}</span></p>'
									+'</div>'
								+'</div>'
								+'<div class="dbox" style="padding-top:0px;">'
									+'<div class="form">'
										+'<div>'
											+'<span>姓名：</span>'
											+'<input id="name" type="text" placeholder="请输入姓名"/>'
										+'</div>'
										+'<div>'
											+'<span>手机号：</span>'
											+'<input id="tel" type="tel" placeholder="请输入手机号" maxlength="11"/>'
										+'</div>'
										+'<div>'
											+'<div class="btn_getvec">发送验证码</div>'
											+'<span>验证码：</span>'
											+'<input id="vec" type="tel" placeholder="请输入验证码" maxlength="6"/>'
										+'</div>'
									+'</div>'
								+'</div>'
								+'<div class="dbox" style="padding-top:0px;">'
									+'<div class="form">'
										+'<div class="in_input">'
											+'<span>服务时间：</span>'
											+'<div>'
												+'<select name="" id="apDate">'
													+'<option value=0 disabled="true">预约日期</option>'
												+'</select>'
											+'</div>'
											+'<div>'
												+'<select name="" id="apTime">'
													+'<option value=0 disabled="true">期望时间</option>'
												+'</select>'
											+'</div>'
										+'</div>'
										+'<div id="type">'
											+'<span>服务方式：</span>'
											+'<label for="icheck1">'
												+'<input id="icheck1" class="icheck" type="radio" value="0" name="iCheck" checked="checked">'
												+'<span>到店</span>'
											+'</label>'
											+'{{if storeInfo.serviceToHome}}'
											+'<label for="icheck2">'
												+'<input id="icheck2" class="icheck" type="radio" value="1" name="iCheck">'
												+'<span>上门</span>'
											+'</label>'
											+'{{/if}}'
										+'</div>'

										+'<div class="addr1 textarea" style="display:none;">'
											+'<span>服务地址：</span>'
											+'<textarea id="address" type="text" placeholder="请输入详细地址,方便找到你"/>'
										+'</div>'

										+'<div class="in_input_addr0 addr0">'
											+'<span>门店地址：</span>'
											+'<div>'
												+'{{if storeInfo.userInfo.company.address!=""}}'
													+'<p>{{storeInfo.userInfo.company.address}}</p>'
												+'{{/if}}'
												+'{{if storeInfo.userInfo.company.address==""}}'
													+'{{if storeInfo.userInfo.wxNum!=""}}'
													+'<p style="">未设置店铺地址，可添加微信{{storeInfo.userInfo.wxNum}}与掌柜确认</p>'
													+'{{/if}}'
													+'{{if storeInfo.userInfo.wxNum==""}}'
													+'<p style="line-height:45px;">未设置店铺地址</p>'
													+'{{/if}}'
												+'{{/if}}'
											+'</div>'
										+'</div>'

										+'<div class="textarea">'
											+'<span>预约内容：</span>'
											+'<textarea id="msg" type="text" placeholder="请填写预约内容"/>'
										+'</div>'
									+'</div>'
								+'</div>'
								+'<a id="CheckVec" href="javascript:;" class="iwShop">支付定金</a>'
							+'</div>'
						+'</div>'
						+'<div id="part2" style="display: none;">'
							+'<div class="pTop">'
								+'<a href="javascript:;" class="back"></a>'
								+'<div>支付定金</div>'
							+'</div>'
							+'<div class="main">'
								+'<div class="blank"></div>'
									+'<div class="dabbox ap_storeInfo">'
										+'<div class="storeInfoImg">'
											+'<img src="{{productInfo.images[0]}}?imageView2/1/w/80/h/80" alt="" />'
										+'</div>'
										+'<div class="storeInfoMsg">'
											+'<h2>{{productInfo.title}}</h2>'
											+'<p>价格：<span style="color:#1a1a1a">{{productInfo.price}}</span></p>'
											+'<p>预付定金：<span style="color:#1a1a1a">{{productInfo.price}}</span></p>'
										+'</div>'
								+'</div>'
								+'<div class="dbox" style="padding-top:0px;">'
									+'<div class="form">'
										+'<div class="paytype">'
											+'<img src="images/wxpay.png"/>'
											+'<span>微信支付(推荐)</span>'
											+'<label for="icheck1">'
												+'<input id="icheck1" class="icheck" type="radio" value="0" name="iCheck" checked="checked">'
											+'</label>'
										+'</div>'
									+'</div>'
								+'</div>'
								+'<a id="postOrder" href="javascript:;" class="iwShop">去支付</a>'
							+'</div>'
						+'</div>'
					+'</div>'
				  +'</script>';

	var normalHtml='<script id="tmp1_appoint" type="text/html">'
					+'<div id="page_appoint" class="page_appoint">'
						+'<input type="hidden" value="在线预约" id="wx_title_appoint" />'
					    +'<input type="hidden" value="{{storeInfo.logo}}?imageView2/0/w/320" id="wx_imgUrl_appoint" />'
					    +'<input type="hidden" value="{{storeInfo.userInfo.nickname}}的微官网" id="wx_desc_appoint" />'
						+'<div class="pTop">'
								+'<a href="#page_detail/" class="back"></a>'
								+'<div>预约</div>'
						+'</div>'
						+'<input type="hidden" value="预约" id="title_appoint" />'
							+'<div class="main">'
								+'<div class="blank" style="margin-bottom:-12px;"></div>'
								+'<div class="dbox" style="padding-top:0px;">'
									+'<div class="form">'
										+'<div>'
											+'<span>姓名：</span>'
											+'<input id="name" type="text" placeholder="请输入姓名"/>'
										+'</div>'
										+'<div>'
											+'<span>手机号：</span>'
											+'<input id="tel" type="tel" placeholder="请输入手机号" maxlength="11"/>'
										+'</div>'
                                        +'<div>'
                                            +'<div class="btn_getvec">发送验证码</div>'
                                            +'<span>验证码：</span>'
                                            +'<input id="vec" type="tel" placeholder="请输入验证码" maxlength="6"/>'
                                        +'</div>'
                                    +'</div>'
                                +'</div>'
                                +'<div class="dbox" style="padding-top:0px;">'
                                    +'<div class="form">'
										+'<div class="in_input">'
											+'<span>服务时间：</span>'
											+'<div>'
												+'<select name="" id="apDate">'
													+'<option value=0 disabled="true">预约日期</option>'
												+'</select>'
											+'</div>'
											+'<div>'
												+'<select name="" id="apTime">'
													+'<option value=0 disabled="true">期望时间</option>'
												+'</select>'
											+'</div>'
										+'</div>'
										+'<div id="type">'
											+'<span>服务方式：</span>'
											+'<label for="icheck1">'
												+'<input id="icheck1" class="icheck" type="radio" value="0" name="iCheck" checked="checked">'
												+'<span>到店</span>'
											+'</label>'
											+'{{if storeInfo.serviceToHome}}'
											+'<label for="icheck2">'
												+'<input id="icheck2" class="icheck" type="radio" value="1" name="iCheck">'
												+'<span>上门</span>'
											+'</label>'
											+'{{/if}}'
										+'</div>'

										+'<div class="addr1 textarea" style="display:none;">'
											+'<span>服务地址：</span>'
											+'<textarea id="address" type="text" placeholder="请输入详细地址,方便找到你"/>'
										+'</div>'

										+'<div class="in_input_addr0 addr0">'
											+'<span>门店地址：</span>'
											+'<div>'
												+'{{if storeInfo.userInfo.company.address!=""}}'
													+'<p>{{storeInfo.userInfo.company.address}}</p>'
												+'{{/if}}'
												+'{{if storeInfo.userInfo.company.address==""}}'
													+'{{if storeInfo.userInfo.wxNum!=""}}'
													+'<p style="">未设置店铺地址，可添加微信{{storeInfo.userInfo.wxNum}}与掌柜确认</p>'
													+'{{/if}}'
													+'{{if storeInfo.userInfo.wxNum==""}}'
													+'<p style="line-height:45px;">未设置店铺地址</p>'
													+'{{/if}}'
												+'{{/if}}'
											+'</div>'
										+'</div>'

										+'<div class="textarea">'
											+'<span>预约内容：</span>'
											+'<textarea id="msg" type="text" placeholder="请填写预约内容"/>'
										+'</div>'
									+'</div>'
								+'</div>'
								+'<a id="postForm" href="javascript:;" class="iwShop">提交预约</a>'
							+'</div>'
						+'</div>'
					+'</div>'
				  +'</script>';
	c.exports={
		tmpHtml:tmpHtml,
		normalHtml:normalHtml
	};
});