define("page/page_fwdetail_temp", function(a, b, c) {
	// js引擎模板
	var tmpHtml = '<script id="tmp_fwdetail" type="text/html">' 
					+'<div id="page_fwdetail" class="page_fwdetail{{productInfo._id}}">'
						+'<input type="hidden" value="{{productInfo.title}}，￥{{productInfo.price}}" id="wx_title_fwdetail" />'
						+'<input type="hidden" value="{{productInfo.images[0]}}?imageView2/0/w/320" id="wx_imgUrl_fwdetail" />'
						+'<input type="hidden" value="{{productInfo.title}}，￥{{productInfo.price}}，{{productInfo.description}}" id="wx_desc_fwdetail" />'
						+'{{if storeInfo.dev2 == false}}'
						+'<div class="pTop">'
							+'<a href="#page_detail" class="back"></a>'
							+'<div style="display:none;">服务详情</div>'
						+'</div>'
						+'{{/if}}'
						+'<input type="hidden" value="服务详情 - {{productInfo.title}}" id="title_fwdetail" />'
							+'<div class="main">'
								+'<div class="pdetail">'
									+'<img src="{{productInfo.images[0]}}?imageView2/0/h/640" alt="" />'
									+'<h2 class="title">{{productInfo.title}}</h2>'
									+'<div class="fw_price"><span>￥  {{productInfo.price}}</span>'
									+'<span>{{qua}}</span></div>'
									+'<p id="prodesc">{{productInfo.description}}</p>'
									+'{{if tags.length!=0 }}'
										+'<div class="tagarea"><img src="images/icon_Tags.png"><div id="tagscroller"><div>'
										+'{{each tags as value i}}'
										+'<span>{{value}}</span>'
										+'{{/each}}'
									+'</div></div></div>{{/if}}'
								+'</div>'
//								
								+'<a href="#page_detail" style="color:#333">'
									+'<div class="s-de pdetail">'
									
										+'<div class="s-head">{{if storeInfo.logo!=""}}'
							 			+'<img src="{{storeInfo.logo}}?imageView2/0/w/80" alt=""  />'
							 			+'{{/if}}'
							 			
							 			+'{{if storeInfo.logo==""}}'
							 			+'<img src="images/Default_Avater.jpg" alt="" />'
							 			+'{{/if}}</div>'
							 			
										+'<div>'
											+'<h2>{{storeInfo.storeName}}</h2>'
											+'{{if storeInfo.userInfo.wxNum!=""}}'
											+'<p>微信号：{{storeInfo.userInfo.wxNum}}</p>'
											+'{{/if}}'
										+'</div>'
										+'<span>'
											+'<i class="icon-angle-right"></i>'
										+'</span>'
									+'</div>'
								+'</a>'
//
								+'{{if productInfo.images[1]!=null}}'
										+'{{each productInfo.images as value i}}'
											+'{{if i>0}}'
											+'<img src="{{value}}" alt="" />'
											+'{{/if}}'
										+'{{/each}}'
								+'{{/if}}'
								+'{{if storeInfo.dev == false}}'
					 			+'<a href="http://mzg.so/m_index.html" class="iwShop">我也要发布作品</a>'
					 			+'{{/if}}'
					 			+'<div class="blank"></div>'
							+'</div>'
							+'{{if storeInfo.dev2 == false}}'
							+'<div class="prefooter">'
								+'<div class="footer kf1">'
									+'<div class="dbtn">'
										+'<a href="javascript:;" class="wxzx">微信咨询</a>'
									+'</div>'
									+'<div>'
										+'<a href="#page_appoint/{{productInfo._id}}">预约Ta</a>'
									+'</div>'
								+'</div>'
							+'</div>'
							+'{{/if}}'
					+'</div>'
				+ '</script>';
	c.exports=tmpHtml;
});