define("page/page_detail_temp", function(a, b, c) {
	var isc=a("iscroll4/main").create;
	var r_isc=a("iscroll4/main").refresh;
	// js引擎模板
	var tmpHtml = '<script id="tmp_detail" type="text/html">'

						+'<div id="page_detail" class="page_detail">'
							+'<input type="hidden" value="{{storeInfo.userInfo.nickname}}的微官网" id="wx_title_detail" />'
							+'<input type="hidden" value="{{storeInfo.logo}}?imageView2/0/w/160" id="wx_imgUrl_detail" />'
							+'<input type="hidden" value="这个美掌柜手艺很不错，快来看看他的优秀作品吧！" id="wx_desc_detail" />'
							+'<input type="hidden" value="{{storeInfo.storeName}}" id="title_detail" />'
							+'<div id="d2nav">'
						 		+'<div class="s-nav">'
						 			+'<div>'
						 				+'<a class="active" href="javascript:;" id="zpx">作品集</a>'
						 			+'</div>'
						 			+'<div>'
						 				+'<a href="javascript:;" id="fw">价目表</a>'
						 			+'</div>'
						 			+'<div>'
						 				+'<a href="javascript:;" id="about">简介</a>'
						 			+'</div>'
						 		+'</div>'
						 	+'</div>'
						 	+'<div class="main" id="wd0">'
							 	+'<div class="scroller">'
//									+'<div class="blank"></div>'
									+'<div id="COVER"></div>'
							 		+'<div class="dhead"><div></div></div>'
							 		+'<div class="s-logo">'
							 			+'{{if storeInfo.topBanner!=""}}'
							 			+'<img src="{{storeInfo.topBanner}}?imageView2/0/h/480" alt="" />'
							 			+'{{/if}}'
							 			+'{{if storeInfo.topBanner==""}}'
							 			+'<img src="images/banner.png" alt="" />'
							 			+'{{/if}}' 
							 		+'</div>'
							 		+'<div class="s-de">'
							 			
							 			+'{{if storeInfo.logo!=""}}'
							 			+'<div class="s-head"><img src="{{storeInfo.logo}}?imageView2/0/w/160" alt=""/></div>'
							 			+'{{/if}}'
							 			
							 			+'{{if storeInfo.logo==""}}'
							 			+'<div class="s-head"><img src="images/Default_Avater.jpg" alt="" class="s-head" /></div>'
							 			+'{{/if}}'
							 			
							 			+'<div>'
							 				+'<h2 style="font-size:14px;">{{storeInfo.storeName}}</h2>'
							 				+'<p style="font-size:12px;">微信号：{{storeInfo.userInfo.wxNum}}</p>'
							 			+'</div>'
							 			
							 		+'</div>'
							 		+'<div id="dnav">'
								 		+'<div class="s-nav">'
								 			+'<div>'
								 				+'<a class="active" href="javascript:;" id="zpx">作品集</a>'
								 			+'</div>'
								 			+'<div>'
								 				+'<a href="javascript:;" id="fw">价目表</a>'
								 			+'</div>'
								 			+'<div>'
								 				+'<a href="javascript:;" id="about">简介</a>'
								 			+'</div>'
								 		+'</div>'
								 	+'</div>'
							 		+'<div id="tab">'
							 			+'<div class="prolist _zpx">'
							 				+'{{each list as value i}}'
							 				+'{{if list.length==(i+1)}}'
							 					+'<input type="hidden" id="lastid" value="{{value._id}}"/>'
							 				+'{{/if}}'
							 				+'{{/each}}'
									 		+'<ul class="pro" id="Gallery">'
									 		 +'{{each list as value i}}'
									        	+'<li><div>'
									        		+'<a href="#page_pdetail/{{value._id}}">'
									 					+'<img src="{{value.images[0]}}?imageView2/0/h/320" alt="" />'
									 					+'<div class="pro_detail">'
									 						+'<p class="pro_name">{{value.title}}</p>'
									 						+'<p class="pro_fee">{{value.images.length}}张</p>'
									 					+'</div>'
									 				+'</a>'
									        	+'</div></li>'
									    	+'{{/each}}'
									 		+'</ul>'
									 		+'<div id="pullUp1" class="ready" data-is="active"><span class="pullUpIcon"></span><span class="pullUpLabel">加载更多</span></div>'
									 		+'{{if storeInfo.dev == false}}'
								 			+'<a href="http://mzg.so/m_index.html" class="iwShop">我也要开通微名片</a>'
								 			+'{{/if}}'
								 			+'{{if storeInfo.dev == true}}'
								 			+'<div class="blank"></div>'
								 			+'{{/if}}'
									 	+'</div>'
									 	+'<div class="prolist _fw">'
									 		+'<p style="text-align:center;margin-top:30px;color:#555;">正在加载中</p>'
									 	+'</div>'
								 		+'<div id="aboutMe">'
								 			+'<div class="d2abbox">'
								 				+'{{if storeInfo.userInfo.faith==""}}'
								 					+'{{if storeInfo.userInfo.wxNum==""}}'
								 					+'<div class="in_des">店主生意太忙，还未填写店铺介绍~</div>'
								 					+'{{/if}}'
								 					+'{{if storeInfo.userInfo.wxNum!=""}}'
								 					+'<div class="in_des">店主生意太忙，还未填写店铺介绍，可添加店主微信{{storeInfo.userInfo.wxNum}}咨询。</div>'
								 					+'{{/if}}'
								 				+'{{/if}}'
								 				+'{{if storeInfo.userInfo.faith!=""}}'
								 					+'<div id="faith" class="in_des">{{storeInfo.userInfo.faith}}</div>'
								 				+'{{/if}}'
								 			+'</div>'
								 			+'{{if typeof(storeInfo.userInfo.company.name)!="undefined"}}' 
								 				+'<div class="d2abbox">'
//									 				+'<a href="javascript:;" class="btn_map">查看地图</a>'
									 				+'<h2><img src="images/icon_Pointer.png">{{storeInfo.userInfo.company.name}}</h2>'
										 			+'<div class="in_des in_addr">{{storeInfo.userInfo.company.address}}</div>'
										 			+'{{if storeInfo.openTime!=""}}'
										 				+'<div class="in_ti"><img src="images/icon_Speedometer.png">{{storeInfo.openTime}}</div>'
										 			+'{{/if}}'
								 				+'</div>'
								 				+'{{if storeInfo.serviceArea!=""}}'
									 				+'<div class="d2abbox">'
									 					+'<div class="in_des">服务范围：{{storeInfo.serviceArea}}</div>'
									 				+'</div>'
								 				+'{{/if}}'
								 			+'{{/if}}'
								 				
								 			+'{{if storeInfo.dev == false}}'
								 			+'<a href="http://mzg.so/m_index.html" class="iwShop">我也要开通微名片</a>'
								 			+'{{/if}}'	
								 		+'</div>'
								 	+'</div>'
								+'</div>'
						 	+'</div>'
						 	+'{{if storeInfo.dev2 == false}}'
						 	+'<div class="prefooter">'
								+'<div class="footer kf1">'
									+'<div class="dbtn">'
										+'<a href="javascript:;" class="wxzx">微信咨询</a>'
									+'</div>'
									+'<div>'
										+'<a href="#page_appoint/">预约Ta</a>'
									+'</div>'
								+'</div>'
							+'</div>'
							+'{{/if}}'
						 +'</div>'
 					+'</script>';
	c.exports=tmpHtml;
});